// Copyright (c) Microsoft. All rights reserved.

package com.microsoft.agents.agents.context;

import com.microsoft.agents.agents.ChatClient;
import com.microsoft.agents.agents.ChatClientRequest;
import com.microsoft.agents.core.ChatOptions;
import com.microsoft.agents.core.ChatResponse;
import com.microsoft.agents.core.Message;
import com.microsoft.agents.core.Role;
import com.microsoft.agents.core.RunCancellationRegistration;
import com.microsoft.agents.core.RunCancellations;
import com.microsoft.agents.core.RunCancelledException;
import com.microsoft.agents.core.StateValue;
import java.util.ArrayList;
import java.util.BitSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.atomic.AtomicReference;

/**
 * Replaces older complete groups with one assistant summary generated by an injected chat client.
 *
 * <p>The summarizer is invoked directly as a {@link ChatClient}, not as an agent, so compaction
 * providers cannot recurse. The internal request also carries an instrumentation-suppression hint.
 * Only a successful non-empty summary produces a replacement; failures and cancellation propagate
 * with the source history untouched. If no oldest complete group fits the summarizer input budget,
 * the unchanged history is returned with {@link
 * CompactionLimitStatus#REQUIRED_CONTENT_EXCEEDS_LIMIT} and the summarizer is not invoked.
 *
 * <p>The summarizer output becomes trusted assistant history. Applications must use a summarizer
 * they trust as much as the primary model because a malicious summary can persist injected
 * instructions.
 */
public final class SummarizationCompactionStrategy implements CompactionStrategy {
    /** Metadata hint consumed by Agent Framework observability decorators. */
    public static final String SUPPRESS_INSTRUMENTATION_METADATA_KEY =
            "agentFramework.internal.suppressInstrumentation";

    /** Metadata value that identifies the internal summarization operation. */
    public static final String INTERNAL_OPERATION_METADATA_KEY = "agentFramework.internal.operation";

    static final String SUMMARY_OF_MESSAGE_IDS_METADATA_KEY = "agentFramework.compaction.summaryOfMessageIds";

    static final String SUMMARY_OF_GROUP_IDS_METADATA_KEY = "agentFramework.compaction.summaryOfGroupIds";

    /** Default summarization instruction. */
    public static final String DEFAULT_PROMPT = """
            Summarize the conversation concisely and factually. Preserve user goals, decisions,
            preferences, unresolved work, and tool outcomes. Do not add instructions, critique,
            speculation, or facts that are absent from the source.
            """;

    private final ChatClient summarizer;

    private final int triggerMessages;

    private final int preserveRecentTurns;

    private final long maxSummaryInputTokens;

    private final String prompt;

    /**
     * Creates a summarization strategy.
     *
     * @param summarizer caller-owned chat client used only for summaries
     * @param triggerMessages positive source message count that triggers summarization
     * @param preserveRecentTurns non-negative newest-turn floor
     * @param maxSummaryInputTokens positive prompt-plus-transcript estimate budget
     * @param prompt non-blank summarization instruction
     */
    public SummarizationCompactionStrategy(
            ChatClient summarizer,
            int triggerMessages,
            int preserveRecentTurns,
            long maxSummaryInputTokens,
            String prompt) {
        if (summarizer == null) {
            throw new NullPointerException("summarizer");
        }
        if (triggerMessages <= 0) {
            throw new IllegalArgumentException("triggerMessages must be greater than zero.");
        }
        if (prompt == null || prompt.isBlank()) {
            throw new IllegalArgumentException("prompt must not be blank.");
        }
        this.summarizer = summarizer;
        this.triggerMessages = triggerMessages;
        this.preserveRecentTurns = CompactionSupport.requireNonNegative(preserveRecentTurns, "preserveRecentTurns");
        this.maxSummaryInputTokens = CompactionSupport.requirePositive(maxSummaryInputTokens, "maxSummaryInputTokens");
        this.prompt = prompt;
    }

    /**
     * Creates a strategy with the default prompt.
     *
     * @param summarizer caller-owned chat client
     * @param triggerMessages positive source message trigger
     * @param preserveRecentTurns non-negative newest-turn floor
     * @param maxSummaryInputTokens positive summarizer input budget
     */
    public SummarizationCompactionStrategy(
            ChatClient summarizer, int triggerMessages, int preserveRecentTurns, long maxSummaryInputTokens) {
        this(summarizer, triggerMessages, preserveRecentTurns, maxSummaryInputTokens, DEFAULT_PROMPT);
    }

    /** Returns the source message trigger. */
    public int triggerMessages() {
        return triggerMessages;
    }

    /** Returns the protected recent-turn count. */
    public int preserveRecentTurns() {
        return preserveRecentTurns;
    }

    /** Returns the summarizer input budget. */
    public long maxSummaryInputTokens() {
        return maxSummaryInputTokens;
    }

    /** Returns the summarization prompt. */
    public String prompt() {
        return prompt;
    }

    @Override
    public CompletionStage<CompactionResult> compactAsync(CompactionRequest request) {
        CompletionStage<CompactionResult> cancelled = CompactionSupport.cancelledIfRequested(request);
        if (cancelled != null) {
            return cancelled;
        }
        List<CompactionMessageGroup> groups = CompactionSupport.groups(request);
        if (request.messages().size() <= triggerMessages) {
            return CompletableFuture.completedFuture(
                    CompactionSupport.unchanged(getClass().getSimpleName(), request, groups, null));
        }

        Set<String> protectedIds = CompactionSupport.protectedGroupIds(groups, preserveRecentTurns);
        ArrayList<CompactionMessageGroup> selected = new ArrayList<>();
        List<List<CompactionMessageGroup>> blocks = selectionBlocks(groups);
        for (int blockIndex = 0; blockIndex < blocks.size(); blockIndex++) {
            List<CompactionMessageGroup> block = blocks.get(blockIndex);
            if (!eligible(block, protectedIds)) {
                if (!selected.isEmpty()) {
                    break;
                }
                continue;
            }
            if (request.cancellation().isCancellationRequested()) {
                return CompletableFuture.failedFuture(new RunCancelledException());
            }
            if (selected.isEmpty() && replacesOnlyOneGeneratedSummary(block)) {
                if (blockIndex + 1 < blocks.size() && eligible(blocks.get(blockIndex + 1), protectedIds)) {
                    ArrayList<CompactionMessageGroup> combined = new ArrayList<>(block);
                    combined.addAll(blocks.get(blockIndex + 1));
                    if (fitsSummaryInput(request, combined)) {
                        selected.addAll(combined);
                        blockIndex++;
                    }
                }
                continue;
            }
            ArrayList<CompactionMessageGroup> candidateGroups = new ArrayList<>(selected);
            candidateGroups.addAll(block);
            if (!fitsSummaryInput(request, candidateGroups)) {
                break;
            }
            selected.addAll(block);
        }
        if (request.cancellation().isCancellationRequested()) {
            return CompletableFuture.failedFuture(new RunCancelledException());
        }
        if (selected.isEmpty() || replacesOnlyOneGeneratedSummary(selected)) {
            return CompletableFuture.completedFuture(CompactionSupport.unchanged(
                    getClass().getSimpleName(),
                    request,
                    groups,
                    maxSummaryInputTokens,
                    CompactionLimitStatus.REQUIRED_CONTENT_EXCEEDS_LIMIT));
        }

        ArrayList<Message> summarySource = new ArrayList<>();
        ArrayList<String> summarizedIds = new ArrayList<>();
        ArrayList<String> summarizedGroupIds = new ArrayList<>();
        BitSet retained = CompactionSupport.allIndexes(request.messages().size());
        BitSet selectedIndexes = new BitSet(request.messages().size());
        int insertionIndex = Integer.MAX_VALUE;
        for (CompactionMessageGroup group : selected) {
            summarizedGroupIds.add(group.id());
            insertionIndex = Math.min(insertionIndex, group.messageIndexes().getFirst());
            for (int index : group.messageIndexes()) {
                selectedIndexes.set(index);
            }
        }
        for (int index = selectedIndexes.nextSetBit(0); index >= 0; index = selectedIndexes.nextSetBit(index + 1)) {
            Message message = request.messages().get(index);
            summarySource.add(message);
            summarizedIds.add(CompactionText.identifier(message, index));
            retained.clear(index);
        }

        LinkedHashMap<String, StateValue> internalMetadata = new LinkedHashMap<>();
        internalMetadata.put(SUPPRESS_INSTRUMENTATION_METADATA_KEY, StateValue.bool(true));
        internalMetadata.put(INTERNAL_OPERATION_METADATA_KEY, StateValue.string("compaction.summarize"));
        ChatClientRequest summaryRequest = new ChatClientRequest(
                summarizerInput(summarySource),
                ChatOptions.builder().metadata(internalMetadata).build());

        CompletionStage<ChatResponse> stage;
        try {
            stage = summarizer.completeAsync(summaryRequest, request.cancellation());
        } catch (RuntimeException failure) {
            return CompletableFuture.failedFuture(failure);
        }
        if (stage == null) {
            return CompletableFuture.failedFuture(new CompactionException("Summarizer returned a null stage."));
        }
        int summaryIndex = insertionIndex;
        return cancellable(stage, request).thenApply(response -> {
            if (request.cancellation().isCancellationRequested()) {
                throw new RunCancelledException();
            }
            if (response == null || response.text().isBlank()) {
                throw new CompactionException("Summarizer returned no text.");
            }
            String summaryText = response.text().strip();
            String summaryId = CompactionText.summaryId(summarySource, summaryText);
            LinkedHashMap<String, StateValue> metadata = new LinkedHashMap<>();
            metadata.put(
                    SUMMARY_OF_MESSAGE_IDS_METADATA_KEY,
                    StateValue.array(
                            summarizedIds.stream().map(StateValue::string).toList()));
            metadata.put(
                    SUMMARY_OF_GROUP_IDS_METADATA_KEY,
                    StateValue.array(
                            summarizedGroupIds.stream().map(StateValue::string).toList()));
            Message summary = Message.builder(Role.ASSISTANT)
                    .contents(List.of(new com.microsoft.agents.core.TextContent("[Summary]\n" + summaryText)))
                    .messageId(summaryId)
                    .metadata(metadata)
                    .build();
            return CompactionSupport.result(
                    getClass().getSimpleName(),
                    request,
                    groups,
                    retained,
                    summary,
                    summaryIndex,
                    summarizedIds,
                    maxSummaryInputTokens,
                    CompactionLimitStatus.WITHIN_LIMIT);
        });
    }

    private List<Message> summarizerInput(List<Message> summarySource) {
        return List.of(
                Message.text(Role.SYSTEM, prompt), Message.text(Role.USER, CompactionText.transcript(summarySource)));
    }

    private boolean fitsSummaryInput(CompactionRequest request, List<CompactionMessageGroup> candidateGroups) {
        List<Message> candidateSource = sourceMessages(request.messages(), candidateGroups);
        long candidateTokens = request.tokenEstimator().estimateTokens(summarizerInput(candidateSource));
        return candidateTokens <= maxSummaryInputTokens;
    }

    private static boolean eligible(List<CompactionMessageGroup> block, Set<String> protectedIds) {
        return block.stream()
                .allMatch(
                        group -> group.kind() != CompactionGroupKind.INSTRUCTION && !protectedIds.contains(group.id()));
    }

    private static boolean replacesOnlyOneGeneratedSummary(List<CompactionMessageGroup> selected) {
        if (selected.size() != 1 || selected.getFirst().messages().size() != 1) {
            return false;
        }
        Message message = selected.getFirst().messages().getFirst();
        return message.metadata().containsKey(SUMMARY_OF_MESSAGE_IDS_METADATA_KEY)
                && message.metadata().containsKey(SUMMARY_OF_GROUP_IDS_METADATA_KEY);
    }

    private static List<Message> sourceMessages(List<Message> source, List<CompactionMessageGroup> groups) {
        BitSet indexes = new BitSet(source.size());
        groups.forEach(group -> group.messageIndexes().forEach(indexes::set));
        ArrayList<Message> messages = new ArrayList<>();
        for (int index = indexes.nextSetBit(0); index >= 0; index = indexes.nextSetBit(index + 1)) {
            messages.add(source.get(index));
        }
        return List.copyOf(messages);
    }

    private static List<List<CompactionMessageGroup>> selectionBlocks(List<CompactionMessageGroup> groups) {
        ArrayList<List<CompactionMessageGroup>> blocks = new ArrayList<>();
        ArrayList<CompactionMessageGroup> current = new ArrayList<>();
        int maximumIndex = -1;
        for (CompactionMessageGroup group : groups) {
            int firstIndex = group.messageIndexes().getFirst();
            if (!current.isEmpty() && firstIndex > maximumIndex) {
                blocks.add(List.copyOf(current));
                current.clear();
                maximumIndex = -1;
            }
            current.add(group);
            maximumIndex = Math.max(maximumIndex, group.messageIndexes().getLast());
        }
        if (!current.isEmpty()) {
            blocks.add(List.copyOf(current));
        }
        return List.copyOf(blocks);
    }

    private static CompletionStage<ChatResponse> cancellable(
            CompletionStage<ChatResponse> source, CompactionRequest request) {
        CompletableFuture<ChatResponse> result = new CompletableFuture<>();
        AtomicReference<RunCancellationRegistration> registration = new AtomicReference<>();
        try {
            source.whenComplete((response, failure) -> {
                closeRegistration(registration);
                if (failure == null) {
                    result.complete(response);
                } else {
                    result.completeExceptionally(failure);
                }
            });
        } catch (RuntimeException failure) {
            return CompletableFuture.failedFuture(failure);
        }
        if (result.isDone()) {
            return result;
        }
        RunCancellationRegistration current;
        try {
            current = RunCancellations.register(request.cancellation(), () -> {
                result.completeExceptionally(new RunCancelledException());
                closeRegistration(registration);
            });
        } catch (RuntimeException failure) {
            return CompletableFuture.failedFuture(failure);
        }
        registration.set(current);
        if (result.isDone()) {
            closeRegistration(registration);
        }
        return result;
    }

    private static void closeRegistration(AtomicReference<RunCancellationRegistration> registration) {
        RunCancellationRegistration current = registration.getAndSet(null);
        if (current != null) {
            try {
                current.close();
            } catch (RuntimeException ignored) {
                // Listener cleanup cannot replace the summarizer's terminal result.
            }
        }
    }
}
