plugins {
    id("com.microsoft.agents.java-platform")
}

description = "Dependency constraints for the Agent Framework Java release train."

dependencies {
    constraints {
        api(project(":agent-framework-core"))
        api(project(":agent-framework-tools"))
        api(project(":agent-framework-tools-shell"))
        api(project(":agent-framework-agents"))
        api(project(":agent-framework-harness"))
        api(project(":agent-framework-workflows"))
        api(project(":agent-framework-workflows-declarative"))
        api(project(":agent-framework-orchestrations"))
        api(project(":agent-framework-observability"))
        api(project(":agent-framework-reactor-adapter"))
        api(project(":agent-framework-mcp"))
        api(project(":agent-framework-hosting-mcp"))
        api(project(":agent-framework-a2a"))
        api(project(":agent-framework-hosting-a2a"))
        api(project(":agent-framework-hosting-telegram"))
        api(project(":agent-framework-agui"))
        api(project(":agent-framework-hosting"))
        api(project(":agent-framework-hosting-http"))
        api(project(":agent-framework-hosting-openai"))
        api(project(":agent-framework-hosting-spring"))
        api(project(":agent-framework-hosting-agui"))
        api(project(":agent-framework-hosting-agui-spring"))
        api(project(":agent-framework-openai"))
        api(project(":agent-framework-azure-openai"))
        api(project(":agent-framework-azure-authentication"))
        api(project(":agent-framework-azure-ai-persistent"))
        api(project(":agent-framework-evaluation"))
        api(project(":agent-framework-foundry"))
        api(project(":agent-framework-foundry-hosting"))
        api(project(":agent-framework-foundry-evaluations"))
        api(project(":agent-framework-azure-content-understanding"))
        api(project(":agent-framework-azure-cosmos"))
        api(project(":agent-framework-azure-cosmos-memory"))
        api(project(":agent-framework-azure-ai-search"))
        api(project(":agent-framework-valkey"))
        api(project(":agent-framework-mem0"))
        api(project(":agent-framework-purview"))
        api(project(":agent-framework-anthropic"))
        api(project(":agent-framework-bedrock"))
        api(project(":agent-framework-gemini"))
        api(project(":agent-framework-mistral"))
        api(project(":agent-framework-ollama"))
        api(project(":agent-framework-foundry-local"))
        api(project(":agent-framework-codeact"))
        api(project(":agent-framework-declarative"))
        api(project(":agent-framework-devui"))
        api(project(":agent-framework-github-copilot"))
        api(project(":agent-framework-chatkit"))
        api(project(":agent-framework-copilotstudio"))
    }
}
